spring:
  application:
    name: API-GATEWAY  cloud:    gateway:      routes:
        - id: USER-SERVICE
          uri: lb://USER-SERVICE
          predicates:          - Path=/user/**
        - id: DEPARTMENT-SERVICE
          uri: lb://DEPARTMENT-SERVICE
          predicates:
          - Path=/department/**


server:
   port: 9191

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
    